package net.ghue.ktp.gradle.settings

import net.ghue.ktp.gradle.lukestack.LukestackPlugin
import net.ghue.ktp.gradle.project.ProjectPlugin
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings
import org.gradle.api.logging.Logging
import org.gradle.toolchains.foojay.FoojayToolchainsConventionPlugin

/** Gradle property selecting the project plugin to auto-apply to every project. */
private const val AUTO_APPLY_KEY = "ktp.plugin"

/** Gradle property naming the root project, since a plugin cannot write the settings script. */
private const val ROOT_NAME_KEY = "rootProject.name"

/**
 * Applies the KTP conventions that live at the settings level, so a consumer's
 * `settings.gradle.kts` shrinks to the plugin repositories plus this plugin. Features:
 * - Root project name: read from the [ROOT_NAME_KEY] entry in `gradle.properties`, so the name
 *   survives checkouts into differently named directories (e.g. Docker build stages).
 * - Project auto-include: every direct subdirectory holding a `build.gradle.kts` or a
 *   `package.json` becomes a project. A conventional frontend needs no Gradle file at all.
 * - KTP coordinates: the plugin jar ships a generated [net.ghue.ktp.lib.KtpLibs] object with
 *   the coordinates of every KTP library, pinned to this plugin's own version, so a single
 *   version declaration rules everything KTP and the libraries can never drift from the
 *   plugin. Settings plugins are visible to every project build script, so consumers just
 *   write `implementation(KtpLibs.stripe)`. Compiled Kotlin on the script classpath resolves
 *   in the IDE unconditionally, unlike version catalogs, which need a committed TOML file.
 * - Toolchains: the Foojay resolver is applied, so a missing JDK is downloaded on demand
 *   instead of failing toolchain resolution.
 * - Project plugin auto-apply: `ktp.plugin=ktp|lukestack` in `gradle.properties` applies that
 *   plugin to every project, removing the per-project `plugins {}` boilerplate.
 */
class SettingsPlugin : Plugin<Settings> {

    override fun apply(settings: Settings) {
        settings.providers.gradleProperty(ROOT_NAME_KEY).orNull?.let {
            settings.rootProject.name = it
        }

        settings.rootDir
            .listFiles()
            .orEmpty()
            .filter { it.isDirectory && !it.name.startsWith(".") && it.name != "buildSrc" }
            .filter { it.resolve("build.gradle.kts").exists() || it.resolve("package.json").exists() }
            .forEach { settings.include(":${it.name}") }

        settings.pluginManager.apply(FoojayToolchainsConventionPlugin::class.java)

        deleteObsoleteCatalog(settings)

        applyProjectPlugin(settings)
    }

    /**
     * Older releases generated a `ktp` version catalog into the consumer's tree and asked for it
     * to be committed. KTP coordinates now come from the compiled [net.ghue.ktp.lib.KtpLibs]
     * object instead, so a leftover file is deleted — but only when its header proves this
     * plugin wrote it. A hand-written file with the same name is left alone.
     */
    private fun deleteObsoleteCatalog(settings: Settings) {
        val staleCatalog = settings.rootDir.resolve("gradle/ktp.versions.toml")
        if (staleCatalog.isFile &&
            staleCatalog.readText().startsWith("# Generated by the KTP settings plugin")) {
            staleCatalog.delete()
            Logging.getLogger(SettingsPlugin::class.java)
                .lifecycle(
                    "Deleted obsolete gradle/ktp.versions.toml; " +
                        "use the KtpLibs accessors instead of the ktp catalog."
                )
        }
    }

    private fun applyProjectPlugin(settings: Settings) {
        when (val pluginName = settings.providers.gradleProperty(AUTO_APPLY_KEY).orNull) {
            null -> {}
            "ktp" ->
                settings.gradle.lifecycle.beforeProject {
                    pluginManager.apply(ProjectPlugin::class.java)
                }
            "lukestack" ->
                settings.gradle.lifecycle.beforeProject {
                    pluginManager.apply(LukestackPlugin::class.java)
                }
            else ->
                error(
                    "File 'gradle.properties', field '$AUTO_APPLY_KEY', has invalid value " +
                        "'$pluginName'. Valid values are: ktp, lukestack."
                )
        }
    }
}
