package net.ghue.ktp.gradle.settings

import net.ghue.ktp.gradle.lukestack.LukestackPlugin
import net.ghue.ktp.gradle.project.ProjectPlugin
import javax.inject.Inject
import net.ghue.ktp.lib.KtpVersion
import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings
import org.gradle.api.model.ObjectFactory
import org.gradle.toolchains.foojay.FoojayToolchainsConventionPlugin

/** Gradle property selecting the project plugin to auto-apply to every project. */
private const val AUTO_APPLY_KEY = "ktp.plugin"

/** Gradle property naming the root project, since a plugin cannot write the settings script. */
private const val ROOT_NAME_KEY = "rootProject.name"

/**
 * Applies the KTP conventions that live at the settings level, so a consumer's
 * `settings.gradle.kts` shrinks to the plugin repositories plus this plugin. Features:
 * - Root project name: read from the [ROOT_NAME_KEY] entry in `gradle.properties`, so the name
 *   survives checkouts into differently named directories (e.g. Docker build stages).
 * - Project auto-include: every direct subdirectory holding a `build.gradle.kts` or a
 *   `package.json` becomes a project. A conventional frontend needs no Gradle file at all.
 * - Version catalog: a `ktp` catalog (accessors `ktp.stripe`, `ktp.gcp.auth`, ...) with every
 *   KTP library and plugin, pinned to this plugin's own version, so a single version
 *   declaration rules everything KTP and the libraries can never drift from the plugin. It is
 *   materialized as `gradle/ktp.versions.toml` (commit it) rather than DSL entries because IDE
 *   catalog support only resolves accessors backed by a real TOML file.
 * - Toolchains: the Foojay resolver is applied, so a missing JDK is downloaded on demand
 *   instead of failing toolchain resolution.
 * - Project plugin auto-apply: `ktp.plugin=ktp|lukestack` in `gradle.properties` applies that
 *   plugin to every project, removing the per-project `plugins {}` boilerplate.
 */
class SettingsPlugin @Inject constructor(private val objects: ObjectFactory) : Plugin<Settings> {

    override fun apply(settings: Settings) {
        settings.providers.gradleProperty(ROOT_NAME_KEY).orNull?.let {
            settings.rootProject.name = it
        }

        settings.rootDir
            .listFiles()
            .orEmpty()
            .filter { it.isDirectory && !it.name.startsWith(".") && it.name != "buildSrc" }
            .filter { it.resolve("build.gradle.kts").exists() || it.resolve("package.json").exists() }
            .forEach { settings.include(":${it.name}") }

        settings.pluginManager.apply(FoojayToolchainsConventionPlugin::class.java)

        val catalogFile = settings.rootDir.resolve("gradle/ktp.versions.toml")
        val catalogContent = generateCatalog()
        if (!catalogFile.exists() || catalogFile.readText() != catalogContent) {
            catalogFile.parentFile.mkdirs()
            catalogFile.writeText(catalogContent)
        }
        settings.dependencyResolutionManagement {
            versionCatalogs { create("ktp") { from(objects.fileCollection().from(catalogFile)) } }
        }

        applyProjectPlugin(settings)
    }

    /**
     * The `ktp` catalog as a TOML file. Library aliases drop the `ktp-` prefix so accessors read
     * `ktp.stripe`, not `ktp.ktp.stripe`.
     */
    private fun generateCatalog(): String = buildString {
        appendLine("# Generated by the KTP settings plugin; do not edit, but do commit it so")
        appendLine("# the IDE can resolve the accessors before the first sync.")
        appendLine("[versions]")
        appendLine("ktp = \"${KtpVersion.VERSION}\"")
        appendLine()
        appendLine("[libraries]")
        appendLine("koin-bom = { module = \"io.insert-koin:koin-bom\", version = \"${KtpVersion.KOIN}\" }")
        KtpVersion.libs.forEach {
            val alias = it.removePrefix("ktp-")
            appendLine("$alias = { module = \"${KtpVersion.GROUP}:$it\", version.ref = \"ktp\" }")
        }
        appendLine()
        appendLine("[plugins]")
        appendLine("ktp = { id = \"${KtpVersion.GROUP}\", version.ref = \"ktp\" }")
        appendLine("settings = { id = \"${KtpVersion.GROUP}.settings\", version.ref = \"ktp\" }")
        appendLine("lukestack = { id = \"${KtpVersion.GROUP}.lukestack\", version.ref = \"ktp\" }")
    }

    private fun applyProjectPlugin(settings: Settings) {
        when (val pluginName = settings.providers.gradleProperty(AUTO_APPLY_KEY).orNull) {
            null -> {}
            "ktp" ->
                settings.gradle.lifecycle.beforeProject {
                    pluginManager.apply(ProjectPlugin::class.java)
                }
            "lukestack" ->
                settings.gradle.lifecycle.beforeProject {
                    pluginManager.apply(LukestackPlugin::class.java)
                }
            else ->
                error(
                    "File 'gradle.properties', field '$AUTO_APPLY_KEY', has invalid value " +
                        "'$pluginName'. Valid values are: ktp, lukestack."
                )
        }
    }
}
